name: myapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HELPER
  equatable: ^2.0.5
  logger: ^2.2.0
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  environment_config: ^3.1.0
  url_launcher: ^6.2.5
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  connectivity_plus: ^6.0.1
  version: ^3.0.2
  intl: ^0.19.0
  permission_handler: ^11.3.1
  share_plus: ^7.2.2
  validators: ^3.0.0
  http_parser: ^4.0.2

  # WIDGET
  photo_view: ^0.14.0
  modal_bottom_sheet: ^3.0.0-pre
  bot_toast: ^4.1.3
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0
  flutter_slidable: ^3.1.0
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  scrollable_positioned_list: ^0.3.8
  webview_flutter: ^4.7.0

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.5
  go_router: ^13.2.2
  get_it: ^7.6.7

  # FIREBASE
  firebase_core: ^2.27.0
  firebase_analytics: ^10.8.9
  firebase_app_check: ^0.2.1+17
  firebase_crashlytics: ^3.4.18
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  firebase_remote_config: ^4.3.17
  firebase_messaging: ^14.7.19
  cloud_firestore: ^4.15.8
  # flutter_local_notifications: ^12.0.4
  # flutter_app_badger: ^1.5.0
  # firebase_dynamic_links: ^5.0.8
  # flutter_facebook_auth: ^5.0.6
  # sign_in_with_apple: ^4.2.0
  # uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/images/
    - assets/images/locale/
    - assets/lotties/
    - assets/svgs/
